### ISSUE TITLE
Empty tag list in json causes App crash

### ISSUE THREAD

**Issue by rohitkaradkar** [BenGoBlue05/UdacityAlumni#42]
### Steps to reproduce
when article have empty tags list, It causes App Crash
```
365/com.google.developer.udacityalumni E/AndroidRuntime: FATAL EXCEPTION: IntentService[AlumIntentService]
                                                                                  Process: com.google.developer.udacityalumni, PID: 1239
                                                                                  java.lang.IllegalArgumentException: n <= 0: 0
                                                                                      at java.util.Random.nextInt(Random.java:182)
                                                                                      at com.google.developer.udacityalumni.service.AlumIntentService.addArticles(AlumIntentService.java:54)
                                                                                      at com.google.developer.udacityalumni.service.AlumIntentService.onHandleIntent(AlumIntentService.java:108)
                                                                                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
```
check last article item in [json response](http://udacity-alumni-api.herokuapp.com/api/v1/articles)

### Expected behavior

[`AlumIntentService`](../blob/5a7a9defa8542ffe8adb8cc374e0766588b14ed2/app/src/main/java/com/google/developer/udacityalumni/service/AlumIntentService.java) should check for empty tag list in json response before using it.

**Comment by PPartisan** [comment]
I noticed this issue earlier this morning and issued a fix that seemed to work. Are you using the most recent version to test? [ Issue #40 ]

**Comment by rohitkaradkar** [comment]
no I wasn't. sorry. 
can I delete this issue ?
